# Configure a DataSource - Spring Boot uses Hikari by default. If the environment
# variables exist, they will be used, otherwise the values after the colon are used.
spring.datasource.driver-class-name=com.nuodb.jdbc.Driver
spring.datasource.url=jdbc:com.nuodb://${NUODB_ADMIN_SERVICE:localhost}/${NUODB_DB_NAME:demo}?schema=USER${PEM_INFO:}
spring.datasource.username=${NUODB_DB_USER:dba}
spring.datasource.password=${NUODB_DB_PASSWORD:dba}
spring.datasource.hikari.maxLifetime=300000

# Set the default profile - use an in-memory map to count visits
spring.profiles.active=in-memory

# Enable Spring Actuator (monitoring endpoints)
#
# Go to http://<host>/actuator in your browser. This will list all the actuator
# endpoints available.
# http://localhost:8080/actuator/beans shows the many, many "beans" Spring creates.
#
# The shutdown actuator cannot be enabled without also importing Spring Security,
# so there is a /kill option in VisitorCountingController instead.
management.endpoints.web.exposure.include=*

# Get rid of Spring Boot's ugly, default, "white-label" error page.
server.error.whitelabel.enabled=false
