# Configure a DataSource - Spring Boot uses Hikari by default. Although we use
# these properties, we have overridden Spring Boot's default DataSource setup
# and replace it by our DataSource configuration class.
#spring.datasource.driver-class-name=com.nuodb.jdbc.Driver
#spring.datasource.url=jdbc:com.nuodb://localhost/demo?schema=user
#spring.datasource.username=${NUODB_DB_USER:dba}
#spring.datasource.password=${NUODB_DB_PASSWORD:dba}

# Set the default profile - use an in-memory map to count visits
#spring.profiles.active=in-memory

# Enable Spring Actuator (monitoring endpoints)
#
# Go to http://<host>/actuator in your browser. This will list all the actuator
# endpoints available.
# http://localhost:8080/actuator/beans shows the many, many "beans" Spring creates.
#
# The shutdown actuator cannot be enabled without also importing Spring Security,
# so there is a /kill option in VisitorCountingController instgead.
management.endpoints.web.exposure.include=*

# Get rid of Spring Boot's ugly, default, "white-label" error page.
server.error.whitelabel.enabled=false

#
spring.datasource.driver-class-name=com.nuodb.jdbc.Driver
spring.datasource.username=${NUODB_DB_USER:dba}
spring.datasource.password=${NUODB_DB_PASSWORD:dba}
spring.datasource.hikari.maxLifetime=300000
spring.profiles.active=jdbc,tls

#---
spring.config.activate.on-profile=no-tls

# Running local database - TLS not enabled
spring.datasource.url=jdbc:com.nuodb://${NUODB_ADMIN_SERVICE:localhost}/${NUODB_DB_NAME:demo}?schema=USER&verifyHostname=false&allowSRPFallback=false

#---
spring.config.activate.on-profile=tls

# Running NuoDBaaS database - TLS enabled
spring.datasource.url=jdbc:com.nuodb://${NUODB_ADMIN_SERVICE:localhost}/${NUODB_DB_NAME:demo}y?schema=USER&trustedCertificates=${NUODB_CA_PEM}&verifyHostname=false&allowSRPFallback=false
